SOCIAL_AUTH_TWITTER_KEY = 'mSxqjMT45ICuIP13rQ5BIviHY'
SOCIAL_AUTH_TWITTER_SECRET = 'Cbrd2bSoMae028oxzvoZrbOXJIreNYmu8OeRGtUcMkSMO73LUa'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'http://127.0.0.1:8000/home/'
SOCIAL_AUTH_LOGIN_URL = '/'